trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  PYTHON_HOME: ''

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
    &7z x depot_tools.zip -odepot_tools
    Remove-Item depot_tools.zip
  displayName: 'Fetch depot_tools'
  
- powershell: |
    $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
    $env:Path = "$pwd\depot_tools;" + $env:Path
    cd depot_tools
    ./update_depot_tools.bat
    gclient sync
  displayName: 'Config depot_tools'
  
- script: |
    git clone https://chromium.googlesource.com/angle/angle
    cd angle
    gclient config https://chromium.googlesource.com/angle/angle
    gclient sync
  displayName: 'Fetch angle repo'

- powershell: |
    choco install llvm
    $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
    $env:Path = "$pwd\depot_tools;" + $env:Path
    refreshenv
    cd angle
    ..\depot_tools\python scripts\bootstrap.py
    (get-command python).Path
    refreshenv
    gclient sync
  displayName: 'Setup angle deps'

- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    cd angle
  displayName: 'Sync angle'

- script: |
    $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
    set PATH=%cd%\depot_tools;%PATH%;
    cd angle
    gn gen out/Build_32 --args='clang_win=\"C:\Program Files\LLVM\" target_cpu=\"x32\"' --ide=vs
    gn gen out/Build_64 --args='clang_win=\"C:\Program Files\LLVM\" target_cpu=\"x64\"' --ide=vs
  displayName: 'Setup build projects'

- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
    cd angle
    cd out\Build_64
    dir
    msbuild all.sln
  displayName: 'Build ANGLE'
