# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
    &7z x depot_tools.zip -odepot_tools
    Remove-Item depot_tools.zip
  displayName: 'Fetch depot_tools'
  
- powershell: |
    $env:Path = "$pwd\depot_tools;" + $env:Path
    cd depot_tools
    gclient
  displayName: 'Config depot_tools'
  
- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    git clone https://chromium.googlesource.com/angle/angle
  displayName: 'Fetch angle repo'

- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    cd angle
    ..\depot_tools\python scripts/bootstrap.py
    gclient sync
  displayName: 'Setup angle deps'

- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    cd angle
    call "..\depot_tools\python.bat"
    git checkout master
    gclient sync
  displayName: 'Sync angle'

- script: |
    choco install llvm
    set PATH=%cd%\depot_tools;%PATH%;
    cd angle
    call "..\depot_tools\python.bat"
    gn gen out/Build_32 --args='clang_win=\"C:\Program Files\LLVM\" target_cpu=\"x32\"' --ide=vs
    gn gen out/Build_64 --args='clang_win=\"C:\Program Files\LLVM\" target_cpu=\"x64\"' --ide=vs
  displayName: 'Setup build projects'

- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
    cd angle
    cd out\Build_64
    msbuild all.sln
  displayName: 'Build ANGLE'
