trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
  DEPOT_TOOLS_METRICS: '0'
  PYTHON_HOME: ''
  ANGLE_REVISION: '6d8e2f873a1a73c48e4138b121efa99c25069dce'
  PYTHONWARNINGS: 'ignore:DEPRECATION::pip._internal.cli.base_command'
  GCLIENT_PY3: '1'

jobs:
- job: Build_ANGLE
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
      &7z x depot_tools.zip -odepot_tools
      Remove-Item depot_tools.zip
    displayName: 'Fetch depot_tools'
  
  - powershell: |
      $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
      $env:Path = "$pwd\depot_tools;" + $env:Path
      cd depot_tools
      ./update_depot_tools.bat
      dir
    displayName: 'Config depot_tools'
  
  - script: |
      del C:\ProgramData\Chocolatey\bin\pytho*.exe
      git clone https://chromium.googlesource.com/angle/angle
      cd angle
    displayName: 'Fetch angle repo'

  - powershell: |
      $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
      $env:Path = "$pwd\depot_tools;" + $env:Path
      refreshenv
      cd angle
      python scripts\bootstrap.py
      refreshenv
      gclient sync --revision=$(ANGLE_REVISION)
    displayName: 'Setup angle deps'

  - script: |
      set PATH=%cd%\depot_tools;%PATH%;
      cd angle
    displayName: 'Sync angle'

  - powershell: |
      choco install llvm 2>&1>$null
      $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
      $env:Path = "$pwd\depot_tools;" + $env:Path
      python -m pip --disable-pip-version-check install pywin32
      cd angle
      gn gen out/Build_32 --args='is_clang=true is_debug=false use_custom_libcxx=true angle_is_winuwp=true angle_enable_trace=true is_component_build=false angle_enable_vulkan=true angle_enable_d3d9=true angle_enable_d3d11=true target_cpu=\"x86\"'
      gn gen out/Build_64 --args='is_clang=true is_debug=false use_custom_libcxx=true angle_is_winuwp=true angle_enable_trace=true is_component_build=false angle_enable_vulkan=true angle_enable_d3d9=true angle_enable_d3d11=true  target_cpu=\"x64\"'
    displayName: 'Setup build projects'

  - powershell: |
      $env:Path = "$pwd\depot_tools;" + $env:Path
      &("C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat")
      New-Item -Name "x64" -ItemType "directory" 
      New-Item -Name "x86" -ItemType "directory"
      New-Item -Name "lib" -ItemType "directory"
      New-Item -Name "Binaries" -ItemType "directory"
      cd angle
      autoninja -C out\Build_64 libANGLE
      autoninja -C out\Build_64 libEGL 
      autoninja -C out\Build_64 libGL 
      autoninja -C out\Build_64 libGLESv1_CM 
      autoninja -C out\Build_64 libGLESv2 
      Copy-Item -Path "out\Build_64\*.lib" -Destination "..\x64" -Recurse 
      Copy-Item -Path "out\Build_64\*.pdb" -Destination "..\x64" -Recurse 
      Copy-Item -Path "out\Build_64\*.exe" -Destination "..\x64" -Recurse 
      Copy-Item -Path "out\Build_64\*.dll" -Destination "..\x64" -Recurse
      Remove-Item -LiteralPath "out\Build_64" -Force -Recurse  
      autoninja -C out\Build_32 libANGLE 
      autoninja -C out\Build_32 libEGL 
      autoninja -C out\Build_32 libGL 
      autoninja -C out\Build_32 libGLESv1_CM 
      autoninja -C out\Build_32 libGLESv2 
      Copy-Item -Path "out\Build_32\*.lib" -Destination "..\x86" -Recurse 
      Copy-Item -Path "out\Build_32\*.pdb" -Destination "..\x86" -Recurse 
      Copy-Item -Path "out\Build_32\*.exe" -Destination "..\x86" -Recurse 
      Copy-Item -Path "out\Build_32\*.dll" -Destination "..\x86" -Recurse
      Remove-Item -LiteralPath "out\Build_32" -Force -Recurse 
    displayName: 'Build ANGLE'

  - powershell: |
      Move-Item -Path "x64" -Destination "lib"
      Move-Item -Path "x86" -Destination "lib"
      Move-Item -Path "lib" -Destination "Binaries"
      Copy-Item -Path "angle\include" -Destination "Binaries" -Recurse 
      7z a ANGLE.zip Binaries\*
    displayName: 'Copy Binaries'

  - publish: $(Build.SourcesDirectory)/ANGLE.zip
    artifact: ANGLE Binaries

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan Github PAT'
      repositoryName: 'msmshazan/anglebuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(ANGLE_REVISION)'
      title: 'ANGLE Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.SourcesDirectory)/ANGLE.zip'
